### ISSUE TITLE
NEW (GRAPH GALLERY UPDATE): Create a gallery for viewing the graphs of each run. 

### ISSUE THREAD

**Issue by olssone** [olssone/parkit#31]
Follow the diagrams to understand the look and feel of this page. 

1. Update Nav Bar:
![Front-End-Nav drawio (1)](https://github.com/olssone/parkit/assets/147122630/7de8aa78-1379-4ea8-933b-94dbed5681d0)

2. Page Design
![GRAPH-GALLERY-DESIGN drawio](https://github.com/olssone/parkit/assets/147122630/e5165b10-5d8e-4a5a-adab-c5147bc762ab)

There should not be a "Back" button at the first image and a "Next" button at the last image! Keep the theme and colors the same. Green button for save feature.

**Comment by olssone** [comment]
Hint: Make a copy of the png/parkit-data-analytics-graph.png after the system **successfully** shuts down and put it in a new front-end directory called 'gallery'

**Comment by wantzjacob** [comment]
Commit cf23542 has changes for this issue. Not fully finished.

**Comment by olssone** [comment]
Added in 2e4db884842880954a3abf503b73c61ddeeb9aeb

**Comment by olssone** [comment]
Added final error checking for when there are no gallery images.
